name: Keep Render Alive

on:
  schedule:
    # รันทุกๆ 10 นาที
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server
        run: curl -s https://orion-server-lm9e.onrender.com > /dev/null
